default: &default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  
development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
